# Generated by Django 3.2.8 on 2023-07-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('nproductos', models.AutoField(primary_key=True, serialize=False)),
                ('tipoproducto', models.CharField(max_length=100, verbose_name='tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Aparatos',
            fields=[
                ('n_aparato', models.AutoField(primary_key=True, serialize=False)),
                ('uso', models.CharField(max_length=100, verbose_name='uso')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cve_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ape_pa', models.CharField(max_length=100, verbose_name='ape_pa')),
                ('ape_ma', models.CharField(max_length=100, verbose_name='ape_ma')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('certi_med', models.CharField(max_length=100, verbose_name='certi_med')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('membresia', models.CharField(max_length=100, verbose_name='membresia')),
                ('tipo_inscrip', models.CharField(max_length=100, verbose_name='tipo_inscrip')),
                ('fecha_inicio', models.DateField(verbose_name='fecha_inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha_fin')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='monto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cve_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('productostotales', models.IntegerField(verbose_name='productostotales')),
                ('consumo', models.IntegerField(verbose_name='consumo')),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ganancia')),
                ('cantidadventa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cantidadventa')),
            ],
        ),
        migrations.CreateModel(
            name='MM',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100, verbose_name='producto')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='precio')),
            ],
        ),
        migrations.CreateModel(
            name='PE',
            fields=[
                ('servicioreq', models.AutoField(primary_key=True, serialize=False)),
                ('refaccion', models.CharField(max_length=100, verbose_name='refaccion')),
                ('costoserv', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='costoserv')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='total')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cve_p', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_ped', models.IntegerField(verbose_name='cantidad_ped')),
                ('oferta_desc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='oferta_desc')),
                ('totalP', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='totalP')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('cve_pp', models.AutoField(primary_key=True, serialize=False)),
                ('rutina', models.CharField(max_length=100, verbose_name='rutina')),
                ('horario', models.DateTimeField(verbose_name='horario')),
                ('costo_extra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='costo_extra')),
            ],
        ),
        migrations.CreateModel(
            name='PP',
            fields=[
                ('cve_producto', models.AutoField(primary_key=True, serialize=False)),
                ('costoproducto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='costoproducto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='total')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('numerop', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('contraseña', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('cve_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('cve_socio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ape_pa', models.CharField(max_length=100, verbose_name='ape_pa')),
                ('ape_ma', models.CharField(max_length=100, verbose_name='ape_ma')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('cliente_asig', models.CharField(max_length=100, verbose_name='cliente_asig')),
                ('horario', models.DateTimeField(verbose_name='horario')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='salario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('foliov', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('cve_producto', models.CharField(max_length=100, verbose_name='cve_producto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='total')),
            ],
        ),
    ]
