# Generated by Django 3.2.8 on 2023-08-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='almacen',
            name='idproductofk',
            field=models.IntegerField(null=True, verbose_name='idproductofk'),
        ),
        migrations.AddField(
            model_name='aparatos',
            name='cve_rutinafk',
            field=models.IntegerField(null=True, verbose_name='cve_rutinafk'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cve_clientefk',
            field=models.IntegerField(null=True, verbose_name='cve_clientefk'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cve_sociofk',
            field=models.IntegerField(null=True, verbose_name='cve_sociofk'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idproductofk',
            field=models.IntegerField(null=True, verbose_name='idproductofk'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numeropfk',
            field=models.IntegerField(null=True, verbose_name='numeropfk'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicioreqfk',
            field=models.IntegerField(null=True, verbose_name='servicioreqfk'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cve_clientefk',
            field=models.IntegerField(null=True, verbose_name='cve_clientefk'),
        ),
        migrations.AddField(
            model_name='plan',
            name='instructor',
            field=models.CharField(max_length=100, null=True, verbose_name='instructor'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='cve_productofk',
            field=models.IntegerField(null=True, verbose_name='cve_productofk'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='servicioreqfk',
            field=models.IntegerField(null=True, verbose_name='servicioreqfk'),
        ),
        migrations.AddField(
            model_name='registro',
            name='cve_sociofk',
            field=models.IntegerField(null=True, verbose_name='cve_sociofk'),
        ),
        migrations.AddField(
            model_name='rutinas',
            name='cve_clientefk',
            field=models.IntegerField(null=True, verbose_name='cve_clientefk'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='cve_clientefk',
            field=models.IntegerField(null=True, verbose_name='cve_clientefk'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cve_clientefk',
            field=models.IntegerField(null=True, verbose_name='cve_clientefk'),
        ),
        migrations.AddField(
            model_name='venta',
            name='idproductofk',
            field=models.IntegerField(null=True, verbose_name='idproductofk'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidadventa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidadventa'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ganancia'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='pe',
            name='costoserv',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costoserv'),
        ),
        migrations.AlterField(
            model_name='pe',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='oferta_desc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='oferta_desc'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='totalP',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='totalP'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='costo_extra',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo_extra'),
        ),
        migrations.AlterField(
            model_name='pp',
            name='costoproducto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costoproducto'),
        ),
        migrations.AlterField(
            model_name='pp',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total'),
        ),
    ]
