# Generated by Django 3.2.8 on 2023-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0003_auto_20230801_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
                ('producto', models.CharField(max_length=100, verbose_name='producto')),
            ],
        ),
    ]
